# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timepost',
            name='days',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
    ]
